Add extension function metadata for #112
Snektron/vulkan-zig pull request #127
Opened 2024-04-10 23:26 UTC by bluesillybeard

This fixes #112, 

As I note on line 1067, some extensions (`VK_KHR_push_descriptor` and `VK_EXT_full_screen_exclusive`) end up defining the same function twice. The duplicates are simply removed for now, but I am curious if it would be worth exposing the functions within each require separately rather than all at once. It is entirely possible I am misunderstanding the cause of the duplicate functions.

Feel free to commit directly to my fork, and let me know of any issues.

2024-04-26 18:36 UTC, Snektron commented
For some reason this completely escaped my inbox

2024-04-26 19:21 UTC, Snektron requested changes
It would be nice if there were similar types to add the different feature levels, like `vk.features.version_1_0`. I suggest to move the `Info` struct one level up and re-use it (you can use the Feature's `level` as version here). If you don't feel like doing that feel free to leave it and just address the review comments, then I'll do it in a separate PR. Thanks for starting the effort :)

2024-04-26 19:21 UTC, Snektron commented on generator/vulkan/render.zig
> +                for(ext.requires) |require| {
Can you please run zig fmt on the code base? I'll make sure to set up a check for this in CI.

2024-04-26 19:21 UTC, Snektron commented on generator/vulkan/render.zig
> +                            // For now, duplicate functions are just removed,
I feel like theres not much of a problem to add these functions multiple times. Usually one will OR them together using `merge()`, so there is no problem, and it feels more natural anyway. Besides, the logic is currently quadratic. I suggest to just get rid of that code and allow multiple defintions.

2024-04-26 19:21 UTC, Snektron commented on generator/vulkan/render.zig
> +                            .base => continue,
I suggest changing this to `return error.InvalidRegistry` so that we'll get an error if an extension does actually add a base function.

2024-04-26 19:35 UTC, bluesillybeard commented
I'll get working on this, I don't have a ton of free time so it will take at least a few days

2024-04-26 19:48 UTC, Snektron commented
No problem. If you feel that you don't have enough time, lmk and I will take it over :)

Oh, additionally you might want to rebase on the latest master to get the CI green.

2024-04-27 02:50 UTC, bluesillybeard commented
I've applied the easy suggestions, although GitHub seems to have gotten confused and still thinks my branch is behind.

I'll start working on adding feature levels (`k.features.version_1_0`, etc), it doesn't look like it will be too difficult.

2024-04-27 03:35 UTC, bluesillybeard commented
Rediscovered why duplicate functions were removed: it creates a compile error in the resulting `vk.zig`:
```
zig-cache/o/d4cdcc7a0a71bb76b0ba2ce4deeb196a/vk.zig:17309:14: error: duplicate struct field name
            .cmdPushDescriptorSetWithTemplateKHR = true,
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
zig-cache/o/d4cdcc7a0a71bb76b0ba2ce4deeb196a/vk.zig:17310:14: note: duplicate name here
            .cmdPushDescriptorSetWithTemplateKHR = true,
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
zig-cache/o/d4cdcc7a0a71bb76b0ba2ce4deeb196a/vk.zig:17307:30: note: struct declared here
        .device_functions = .{
```

2024-04-27 04:35 UTC, bluesillybeard commented
This was a lot simpler than I thought it would be, so I'm already done

2024-04-28 08:38 UTC, Snektron commented
Looks pretty good. Thanks for also updating the example, that was a good idea. Im considering some additional changes that make the wrapper initialization process a little cleaner, but I think we should defer that to a separate pull request. Thanks for the work and cooperation! :)

2024-04-28 08:38 UTC, merged

2024-04-28 15:15 UTC, bluesillybeard commented
You're welcome! :+1: